version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building the application"
      - echo "No build steps required for static site"

artifacts:
  files:
    - '**/*'  # Includes everything in the repo